language: csharp
solution: jsreport.Binary.Linux.sln
mono: none
sudo: required
dotnet: 2.0.0
dist: trusty
script:
 - chmod +x jsreport.Binary.Linux/chrome.sh
 - ./jsreport.Binary.Linux/chrome.sh
 - dotnet restore
 - sudo apt-get install -y wget zip
 - chmod +x jsreport.Binary.Linux/download.sh
 - cd jsreport.Binary.Linux.Test && dotnet test
 