image: Visual Studio 2017
artifacts:
  - path: '**\jsreport.Binary.Linux*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.Binary.Linux.sln
before_build:
  - cmd: dotnet restore
  - cmd: cd jsreport.Binary.Linux&&Powershell.exe -ExecutionPolicy ByPass -File download.ps1
deploy:
  provider: NuGet
  api_key:
    secure: Ok6nZu8obJRRE9qRHzNrQ9/B+rzXMCq3Bm3PYwkRvrKKksANcUbhZij+lTmVbUHL
  on:
    appveyor_repo_tag: true
test_script:
- cd jsreport.Binary.Linux.Test
- dotnet test

